### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by lencioni**
```sh
yarn upgrade && yarn upgrade jimp@latest
```

### CODE REVIEW

**Comment by trotzig** [comment]
This repo isn't used any more. Sorry, should have mentioned this in the readme.

**Comment by trotzig** [comment]
The code was brought over to the regular happo.io library.

**Comment by lencioni** [comment]
oh, ok. wherps!

**Comment by lencioni** [comment]
I think I'm going to merge this anyway

**Pull request merged**
